name: rideshare
description: "A campus ride-sharing app for VIT students."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # HTTP & Networking
  http: ^1.2.2
  
  # Local Storage
  shared_preferences: ^2.3.3
  
  # Date/Time Formatting
  intl: ^0.20.1
  
  # Typography
  google_fonts: ^6.2.1
  socket_io_client: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app-logo.png"
  adaptive_icon_background: "#0F766E"
  adaptive_icon_foreground: "assets/images/app-logo.png"

flutter:
  uses-material-design: true
